language: ruby
rvm:
  - 2.0.0-p247
  - 2.3.1
before_install:
  - gem update --system
  - gem install bundler
install: bundle install
script: bundle exec rspec
after_success: bundle exec gem build sourcerer.gemspec
deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: cli_miami*.gem
    api_key:
      secure: oMOVrrP3KeQZJHc3jxoNzfQkbiAZUsbIx6JaU6XDsNcJJf7miYLbt1t+UPeJGAK73tqCU4IioMVJvyPY5/lyZx+GdyFMqhATHm7RkNMHo3s47ejJd+Je3WmxyrjdBVIgCpk3Q+rrW2SLZ2siyAzu7E8uUxUaCHHRiBiRIu92kDg=
    on:
      repo: brewster1134/cli_miami
      ruby: 2.0.0-p247
      tags: true
  - provider: rubygems
    gem: cli_miami
    gemspec: cli_miami.gemspec
    skip_cleanup: true
    api_key:
      secure: plfxLBk1hK0y4EAlsTSLLmBXoVf4OIhKhh8sE1YrhEYn0JC5kQ06zcN4jVW79F6qHKnDWTHYrd/PIUZmytVuPBmUw/6qBKNKzsrvlcQaXJlWTMIjx089e6yvsQFRFycpovI85o7/+TpRZrPG6b//zqKgTcbta1NwOTIvaHaXAe0=
    on:
      branch: master
      repo: brewster1134/cli_miami
      ruby: 2.0.0-p247
      tags: true
